ietf-rats-wg/draft-ietf-rats-msg-wrap

draft-ftbs-rats-msg-wrap.md
Fix #2
Signed-off-by: Thomas Fossati <thomas.fossati@arm.com>
=> more words to the abstract and intro section

draft-ftbs-rats-msg-wrap.md
(also `make fix-lint` to remove trailing whitespaces.)
Fix #8
Signed-off-by: Thomas Fossati <thomas.fossati@arm.com>
=> clarify how to deal with pre-existing CBOR tags

cddl/Makefile, cddl/cmw-array.cddl, cddl/jc.cddl, draft-ftbs-rats-msg-wrap.md
A draft proposal.  Note that this is slightly different from what discussed in the email thread in that the bit map is done using an integer type (rather than a byte string) in order make the CBOR and JSON representations more uniform.
Address #24
=> add a CM indicator to the array form

draft-ftbs-rats-msg-wrap.md
Add IANA paraphernalia to handle registrations of new CM indicators.
Fix #26 
(This PR sits on top of #32, the relevant commit here is [2dddc46](https://github.com/thomas-fossati/draft-ftbs-rats-msg-wrap/pull/33/commits/2dddc46f5fa8030ee09425482c02043460fd3374))
=> Extensibility rules for CM indicators

draft-ietf-rats-msg-wrap.md
Following https://www.rfc-editor.org/rfc/rfc9334.html#name-conceptual-messages
Fix #58
=> align conceptual messages to the plural form

draft-ietf-rats-msg-wrap.md
JWT registry doesn't have "Claim Value Type(s)" field.
=> Remove text in IANA considerations for JWT

draft-ietf-rats-msg-wrap.md
Explicitly mark the unallocated space in the `ind` registry as "unassigned".
This also effectively upper-bounds the number of different CM types to 32.
=> apply IANA suggestion

draft-ietf-rats-msg-wrap.md
This is to address Issue #74. A CMW collection type exists to organize individual attesters' results and not fracture the space of representations of composite attester results. The topologies however are still subject to Verifier scrutiny. If the topology is not present in a measured boot chain signed by some other attester, and the only trusted witness of the complete assembly of a system is the CMW collection itself, we must be careful to ensure that the meaning of labels is properly documented (with a profile) and integrity-protected (with a signature).
Fix #74
=> Add a section detailing CMW collection label usage

cddl/cmw-collection.cddl, draft-ietf-rats-msg-wrap.md
updated cmw-collection.cddl to include a label.
modified prose in section 3.3.1 to better capture the need for integrity protection of label information.
Addresses issue #104
=> Fix label in collections

draft-ietf-rats-msg-wrap.md
Due to the reflow of S3.3 I created a separate section to hold CMW/JWT-related considerations.   That, in turn, necessitated moving the X.509 section to a closer place.
Fix #115
=> More on collections security

draft-ietf-rats-msg-wrap.md
This section is not needed anymore.
=> remove "relation with EAT submods" section

draft-ietf-rats-msg-wrap.md
Based on the [discussion thread](https://mailarchive.ietf.org/arch/msg/rats/rluJsmcttd5i9YWC8LmQwD9yL4A/) on the RATS ML, it looks like it's safer to remove the EAT plug-in at this point and let a future document deal with those.
=> remove EAT submods plug ins

draft-ietf-rats-msg-wrap.md
=> fix: remove contraddictory prose from the examples

cddl/cmw-example-2.json, cddl/frags.mk, cddl/rfc9193.cddl
=> fix: add missing escape in .abnf'd quoted-pair

.github/workflows/archive.yml, .github/workflows/ghpages.yml, .github/workflows/publish.yml, .github/workflows/update.yml, .gitignore, Makefile, draft-ietf-rats-msg-wrap.md
Response attempt at @cabo's question: _"How do application/cmw+cbor with cmwc_t parameters get Content format numbers?"_
=> what to check when assigning new CoAP C-Fs based on `application/cmw`

draft-ietf-rats-msg-wrap.md
Initially intended to address #188, it morphed into the addition of a standalone “privacy considerations” section, which also discusses the point originally raised by @ounsworth.
Fix #188
=> Add privacy considerations

draft-ietf-rats-msg-wrap.md
=> Reflect early allocation for `id-pe-cmw`

draft-ietf-rats-msg-wrap.md
Remove “collection” from the module name since it’s not limited to transporting collections.
=> Rename ASN.1 module

draft-ietf-rats-msg-wrap.md
* since CBOR tags are TN-only, binary compatibility with EAT collections is gone
* requesting CBOR tag 299 was a typo: 399 is what I meant
=> binary-compatibility with EAT collections is gone

cddl/cm-type.cddl, draft-ietf-rats-msg-wrap.md, provisional/cmw-indicators-registry.md
While defining appraisal policies is beyond the scope of the current RATS charter, it makes sense to add a code point for the conceptual message.
Fix #229
=> add appraisal policy to the CM types
