ietf-rats-wg/draft-ietf-rats-msg-wrap

- draft-ftbs-rats-msg-wrap.md
Fix #1
Signed-off-by: Thomas Fossati <thomas.fossati@arm.com>
> add recommendations for registration of evidence media types

- draft-ftbs-rats-msg-wrap.md
Attempt at addressing Carl's confusion on §1:
"In the first sentence of the second paragraph, what is being registered or used interoperably? This would clarify what "their" means in the second sentence. I think the media type notion might need to be introduced before this paragraph."
Partially addresses #15
> clarify intro

- cddl/example-cbor-2.diag
- draft-ftbs-rats-msg-wrap.md
> more examples

- cddl/cmw-array.cddl
- cddl/cmw-cbor-tag.cddl
- draft-ftbs-rats-msg-wrap.md
apply Carl's suggestions and fixes at [1]
[1] https://github.com/thomas-fossati/draft-ftbs-rats-msg-wrap/issues/15#issuecomment-1516870623
> apply Carl's suggestions and fixes

- draft-ftbs-rats-msg-wrap.md
> removing a out-of-scope section

- draft-ftbs-rats-msg-wrap.md
> s/web tokens/web APIs/g

- draft-ietf-rats-msg-wrap.md
> Refine ASN.1 definition of the collection

- draft-ietf-rats-msg-wrap.md
> Increase clarity around wrapping

- draft-ietf-rats-msg-wrap.md
> Rebalance text distribution between Abstract and Intro

- Makefile
- cddl/Makefile
- cddl/cmw.cddl
- cddl/eat-example-1.json
- cddl/eat-start.cddl
- cddl/frags.mk
- draft-ietf-rats-msg-wrap.md
> add CWT example

- draft-ietf-rats-msg-wrap.md
* deal with UCCS
* describe risks associated with collections
Fix #63
> expand security considerations

- draft-ietf-rats-msg-wrap.md
> Clarify x.509 extension wrapping

- cddl/cmw-collection.cddl
- cddl/collection-example-2.diag
- cddl/common-types.cddl
- draft-ietf-rats-msg-wrap.md
> add a type indicator for collections

- materials/ccc-attestation-sig/main.md
- materials/ietf-119/main.md
In preparation for presenting CMW to the attestation SIG
> CCC attestation SIG presentation

- draft-ietf-rats-msg-wrap.md
* Expand CoRIM and add ref
* Expand UCCS
* CMW X.509 extension: relax critical=false to SHOULD
Fix #87
> IoTdir review

- draft-ietf-rats-msg-wrap.md
- provisional/cmw-indicators-registry.md
> create provisional cmw-indicators registry

- draft-ietf-rats-msg-wrap.md
> improve precision when defining the "cmw" claim

- draft-ietf-rats-msg-wrap.md
> rename id-pe-cmw-collection to id-pe-cmw

- draft-ietf-rats-msg-wrap.md
> add CoAP C-F registrations

- materials/ccc-attestation-sig/main.md
- materials/ietf-119/main.md
This is a tweak to the slides I presented at CCC SIG.
> CCC SIG slides tweak

- cddl/cmw-record.cddl
- cddl/cmw-tunnel.cddl
- cddl/common-types.cddl
- draft-ietf-rats-msg-wrap.md
> Use `base64url-string` rather than `base64-string`

- draft-ietf-rats-msg-wrap.md
> Say we also register the CMW media type and Content-Format

- draft-ietf-rats-msg-wrap.md
> Laurence augmented security considerations on collections

- cddl/cmw-cbor-tag.cddl
- cddl/cmw-example-tag-1668576818-def.cddl
- cddl/cmw-example-tag-1668576819-def.cddl
- draft-ietf-rats-msg-wrap.md
> fix CBOR Tag CDDL

- draft-ietf-rats-msg-wrap.md
> fix: consistent use of the term "tag"

- draft-ietf-rats-msg-wrap.md
This is an alternative to #128
> fix: attempt at clarifying ambiguity re: what types are defined

- draft-ietf-rats-msg-wrap.md
> fix: use IANA preferred terminology

- draft-ietf-rats-msg-wrap.md
> collection must have at least one entry

- draft-ietf-rats-msg-wrap.md
> `__cmwc_t` URIs are absolute

- cddl/cmw-collection.cddl
- cddl/cmw-tunnel.cddl
- cddl/collection-example-2.diag
- cddl/collection-example-2.json
- cddl/eat-example-1.json
- cddl/frags.mk
- draft-ietf-rats-msg-wrap.md
> drop tunnels

- cddl/Makefile
- cddl/frags.mk
- cddl/signed-cbor-cmw-headers.cddl
- cddl/signed-cbor-cmw.cddl
- cddl/signed-json-cmw-headers.cddl
- cddl/signed-json-cmw.cddl
- draft-ietf-rats-msg-wrap.md
> add COSE- and JOSE-based signatures

- cddl/Makefile
- cddl/frags.mk
- cddl/signed-cbor-cmw-headers.cddl
- cddl/signed-cbor-cmw.cddl
- cddl/signed-json-cmw-headers.cddl
- cddl/signed-json-cmw.cddl
- draft-ietf-rats-msg-wrap.md
* Add `+jws` Structured Syntax Suffix (e4017c6d2da1d9bc8a44954064f0800c832f4e1a)
* Add `cmw+jws` media type and CoAP C-F (c24c4878845bef2dece8e07451a57aeca4ccb916)
* Add `cmw+cose` media type and CoAP C-F (396eccb0979644892172fd785a0c262c9ffc2e42)
Fix #167 
**NOTE**: this PR branches off #166
> IANA registrations for signed CMW's 

- cddl/frags.mk
> remove dead dependencies (unbreak `main`)

- .github/workflows/ghpages.yml
- draft-ietf-rats-msg-wrap.md
Capturing a suggestion made by @laurencelundblade
> add implementation scalability as an explicit goal

- cddl/cmw-cbor-tag.cddl
- cddl/cmw-example-tag-1668576819-def.cddl
- cddl/cmw-example-tag-1668576935-def.cddl
- draft-ietf-rats-msg-wrap.md
Rename "CMW record" to "Record CMW"
Rename "CMW tag" to "Tag CMW"
Rename "CMW collection" to "Collection CMW"
Fix #148
> Adam's Sweep

- draft-ietf-rats-msg-wrap.md
> add indef-length to record demux

- draft-ietf-rats-msg-wrap.md
> remove (now) redundant §3.3.1

- draft-ietf-rats-msg-wrap.md
> clarify how new Tag CMWs are plugged into the CDDL

- Makefile
- cddl/Makefile
- cddl/signed-cbor-cmw-headers.cddl.in
- cddl/subst.mk
- draft-ietf-rats-msg-wrap.md
See https://github.com/ietf-rats-wg/draft-ietf-rats-msg-wrap/issues/156#issuecomment-2646059143
Partially addresses #156
> Add CoAP C-F to cty

- draft-ietf-rats-msg-wrap.md
> no C-F left behind

- draft-ietf-rats-msg-wrap.md
* add reference to RFC3647
* s/Certificate Authority/Certification Authority/
> Russ's suggestions

- draft-ietf-rats-msg-wrap.md
CMW -> CMV\\/ -> CMVII -> 907
https://roman-numerals.info/CMVII
Fix #201
> use 907 (`CMV\/`) as CMW CBOR Tag number

- draft-ietf-rats-msg-wrap.md
> Describe "conceptual" in the abstract

- cddl/signed-cbor-cmw-headers.cddl.in
- draft-ietf-rats-msg-wrap.md
Addressing Carl’s WGLC review comments.
> Carl’s WGLC review

- cddl/cm-type.cddl
- cddl/common-types.cddl
- cddl/frags.mk
- cddl/signed-cbor-cmw-headers.cddl.in
- draft-ietf-rats-msg-wrap.md
Add a CM Type subsection
Fix #207
(Note that this PR builds on top of Carl’s WGLC review, #217)
> CM Type subsection

- draft-ietf-rats-msg-wrap.md
Some drafts have been promoted to RFC.
> update some refs

- draft-ietf-rats-msg-wrap.md
- materials/ietf-123/main.md
As per hackathon discussion.  Text provided by @ionut-arm
> further clarify “protected"

- draft-ietf-rats-msg-wrap.md
As per https://mailarchive.ietf.org/arch/msg/rats/e2jiOn3pDCKUtYytpV2FkU7_PuY/
> add CM definition to abstract

- draft-ietf-rats-msg-wrap.md
As per [Deb’s request](https://mailarchive.ietf.org/arch/msg/rats/BDfR5ZjvpHV2vq5F6xprxVMUCTo/).
> add CM definition to intro
